//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GriesingerCrypto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GriesingerCrypto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool createaccount_btn_Enabled {
            get {
                object obj = ResourceManager.GetObject("createaccount_btn.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=508,Y=174}.
        /// </summary>
        internal static System.Drawing.Point createaccount_btn_Location {
            get {
                object obj = ResourceManager.GetObject("createaccount_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=135, Height=35}.
        /// </summary>
        internal static System.Drawing.Size createaccount_btn_Size {
            get {
                object obj = ResourceManager.GetObject("createaccount_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int createaccount_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("createaccount_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=524}.
        /// </summary>
        internal static System.Drawing.Point cryptoProgressBar_Location {
            get {
                object obj = ResourceManager.GetObject("cryptoProgressBar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=628, Height=23}.
        /// </summary>
        internal static System.Drawing.Size cryptoProgressBar_Size {
            get {
                object obj = ResourceManager.GetObject("cryptoProgressBar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int cryptoProgressBar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cryptoProgressBar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool decrypt_btn_Enabled {
            get {
                object obj = ResourceManager.GetObject("decrypt_btn.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=165,Y=174}.
        /// </summary>
        internal static System.Drawing.Point decrypt_btn_Location {
            get {
                object obj = ResourceManager.GetObject("decrypt_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=35}.
        /// </summary>
        internal static System.Drawing.Size decrypt_btn_Size {
            get {
                object obj = ResourceManager.GetObject("decrypt_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        internal static int decrypt_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("decrypt_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decryption process had issues and failed. Decryption has ended..
        /// </summary>
        internal static string decryptFailed {
            get {
                return ResourceManager.GetString("decryptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decryption was successful and has ended..
        /// </summary>
        internal static string decryptSuccess {
            get {
                return ResourceManager.GetString("decryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool encrypt_btn_Enabled {
            get {
                object obj = ResourceManager.GetObject("encrypt_btn.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=174}.
        /// </summary>
        internal static System.Drawing.Point encrypt_btn_Location {
            get {
                object obj = ResourceManager.GetObject("encrypt_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=35}.
        /// </summary>
        internal static System.Drawing.Size encrypt_btn_Size {
            get {
                object obj = ResourceManager.GetObject("encrypt_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int encrypt_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("encrypt_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption process had issues and failed. Encryption has ended..
        /// </summary>
        internal static string encryptFailed {
            get {
                return ResourceManager.GetString("encryptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption was successful and has ended..
        /// </summary>
        internal static string encryptSuccess {
            get {
                return ResourceManager.GetString("encryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool file_radiobtn_AutoSize {
            get {
                object obj = ResourceManager.GetObject("file_radiobtn.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=19}.
        /// </summary>
        internal static System.Drawing.Point file_radiobtn_Location {
            get {
                object obj = ResourceManager.GetObject("file_radiobtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=41, Height=17}.
        /// </summary>
        internal static System.Drawing.Size file_radiobtn_Size {
            get {
                object obj = ResourceManager.GetObject("file_radiobtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int file_radiobtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("file_radiobtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=409,Y=120}.
        /// </summary>
        internal static System.Drawing.Point findresource_btn_Location {
            get {
                object obj = ResourceManager.GetObject("findresource_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=90, Height=23}.
        /// </summary>
        internal static System.Drawing.Size findresource_btn_Size {
            get {
                object obj = ResourceManager.GetObject("findresource_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int findresource_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("findresource_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        internal static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool folder_radiobtn_AutoSize {
            get {
                object obj = ResourceManager.GetObject("folder_radiobtn.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=62,Y=19}.
        /// </summary>
        internal static System.Drawing.Point folder_radiobtn_Location {
            get {
                object obj = ResourceManager.GetObject("folder_radiobtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=54, Height=17}.
        /// </summary>
        internal static System.Drawing.Size folder_radiobtn_Size {
            get {
                object obj = ResourceManager.GetObject("folder_radiobtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int folder_radiobtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("folder_radiobtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point folderBrowserDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("folderBrowserDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting key from server.
        /// </summary>
        internal static string getKey {
            get {
                return ResourceManager.GetString("getKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the key from the server. Server message:.
        /// </summary>
        internal static string getKeyError {
            get {
                return ResourceManager.GetString("getKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully acquired the key from the server..
        /// </summary>
        internal static string getKeySuccess {
            get {
                return ResourceManager.GetString("getKeySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=514,Y=96}.
        /// </summary>
        internal static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=129, Height=47}.
        /// </summary>
        internal static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=24}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=98, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=212,Y=24}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=406,Y=24}.
        /// </summary>
        internal static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=53, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=106}.
        /// </summary>
        internal static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=77, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=243}.
        /// </summary>
        internal static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        internal static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=186,Y=17}.
        /// </summary>
        internal static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=259}.
        /// </summary>
        internal static System.Drawing.Point output_txt_Location {
            get {
                object obj = ResourceManager.GetObject("output_txt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool output_txt_Multiline {
            get {
                object obj = ResourceManager.GetObject("output_txt.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ScrollBars similar to Vertical.
        /// </summary>
        internal static System.Windows.Forms.ScrollBars output_txt_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("output_txt.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.ScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=628, Height=259}.
        /// </summary>
        internal static System.Drawing.Size output_txt_Size {
            get {
                object obj = ResourceManager.GetObject("output_txt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int output_txt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("output_txt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=409,Y=40}.
        /// </summary>
        internal static System.Drawing.Point password_txt_Location {
            get {
                object obj = ResourceManager.GetObject("password_txt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=234, Height=20}.
        /// </summary>
        internal static System.Drawing.Size password_txt_Size {
            get {
                object obj = ResourceManager.GetObject("password_txt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int password_txt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("password_txt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool resourcePath_txt_Enabled {
            get {
                object obj = ResourceManager.GetObject("resourcePath_txt.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=122}.
        /// </summary>
        internal static System.Drawing.Point resourcePath_txt_Location {
            get {
                object obj = ResourceManager.GetObject("resourcePath_txt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=376, Height=20}.
        /// </summary>
        internal static System.Drawing.Size resourcePath_txt_Size {
            get {
                object obj = ResourceManager.GetObject("resourcePath_txt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int resourcePath_txt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("resourcePath_txt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=40}.
        /// </summary>
        internal static System.Drawing.Point servername_txt_Location {
            get {
                object obj = ResourceManager.GetObject("servername_txt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=151, Height=20}.
        /// </summary>
        internal static System.Drawing.Size servername_txt_Size {
            get {
                object obj = ResourceManager.GetObject("servername_txt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int servername_txt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("servername_txt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username exists already..
        /// </summary>
        internal static string serverResponse1000 {
            get {
                return ResourceManager.GetString("serverResponse1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. If this error keeps showing up contact the admin of this service..
        /// </summary>
        internal static string serverResponse1001 {
            get {
                return ResourceManager.GetString("serverResponse1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        internal static string serverResponse1002 {
            get {
                return ResourceManager.GetString("serverResponse1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that username does not exist..
        /// </summary>
        internal static string serverResponse1003 {
            get {
                return ResourceManager.GetString("serverResponse1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password, please try again..
        /// </summary>
        internal static string serverResponse1004 {
            get {
                return ResourceManager.GetString("serverResponse1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to create new user.
        /// </summary>
        internal static string startCreateAccount {
            get {
                return ResourceManager.GetString("startCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting decryption, please wait....
        /// </summary>
        internal static string startDecryption {
            get {
                return ResourceManager.GetString("startDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting encryption, please wait....
        /// </summary>
        internal static string startEncryption {
            get {
                return ResourceManager.GetString("startEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting decryption process of {0}: {1}.
        /// </summary>
        internal static string startingDecryptionProcessMessage {
            get {
                return ResourceManager.GetString("startingDecryptionProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting encryption process of {0}: {1}.
        /// </summary>
        internal static string startingEncryptionProcessMessage {
            get {
                return ResourceManager.GetString("startingEncryptionProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping folder after decryption failed..
        /// </summary>
        internal static string unzipFolderFailed {
            get {
                return ResourceManager.GetString("unzipFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to unzip decrypted folder, please wait.
        /// </summary>
        internal static string unzipFolderStart {
            get {
                return ResourceManager.GetString("unzipFolderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping folder was successful..
        /// </summary>
        internal static string unzipFolderSuccess {
            get {
                return ResourceManager.GetString("unzipFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=215,Y=40}.
        /// </summary>
        internal static System.Drawing.Point username_txt_Location {
            get {
                object obj = ResourceManager.GetObject("username_txt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=143, Height=20}.
        /// </summary>
        internal static System.Drawing.Size username_txt_Size {
            get {
                object obj = ResourceManager.GetObject("username_txt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int username_txt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("username_txt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Griesinger Crypto. Please insert the server name and your user credentials above and select a file or folder to encrypt. Encrypted files will always end with the {0} file extension and are threated as files (even that it would be a encrypted folder). So make sure to select the Resource Type &quot;File&quot; if you are looking to decrypt something..
        /// </summary>
        internal static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipping folder for encryption failed..
        /// </summary>
        internal static string zipFolderError {
            get {
                return ResourceManager.GetString("zipFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to zip the folder for encryption, please wait.
        /// </summary>
        internal static string zipFolderForEncrypt {
            get {
                return ResourceManager.GetString("zipFolderForEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipping of folder was successful..
        /// </summary>
        internal static string zipFolderSuccessfull {
            get {
                return ResourceManager.GetString("zipFolderSuccessfull", resourceCulture);
            }
        }
    }
}
